imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/assets.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        socketio_baseurl:    %socketio_baseurl%

jms_di_extra:
    locations:
        all_bundles:             false
        bundles:
            -                    AppBundle
        directories:
            -                    "%kernel.root_dir%/../src"

assetic:
    debug:            %kernel.debug%
    use_controller:   false
    bundles:
        -             AppBundle
    filters:
        cssrewrite:
            apply_to:    "\.css$"
        compass:
            apply_to:    "\.s[a|c]ss$"
        coffee:
            apply_to:    "\.coffee$"

propel:
    path:                     "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path:               "%kernel.root_dir%/../vendor/phing"
    logging:                  %kernel.debug%
    build_properties:
        propel.database:      sqlite
    dbal:
        driver:               sqlite
        dsn:                  sqlite:%database_path%
        options:              {}
        attributes:           {}